### ISSUE TITLE
Explain the difference between cue direction and paragraph direction

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#227]
See https://www.w3.org/Bugs/Public/show_bug.cgi?id=28266

The processing model is OK but it is very unclear what the effect is. We should add a note clarifying this, with an example. In particular clarify that the cue direction (which is determined by the direction of the first paragraph in the cue) affects positioning of the cue, but unicode-bidi:plaintext still makes the direction of each paragraph be isolated from each other.

Also see http://software.hixie.ch/utilities/js/live-dom-viewer/saved/3718

**Comment by zcorpan** [comment]
So given https://github.com/w3c/webvtt/pull/237 there is nothing that depends on the cue direction. Should still add an example here though.

**Comment by r12a** [comment]
I'm wondering whether it might be useful to have a small section that summarises what happens relative to the various aspects of text direction, or a note.

As i understand it, it might say something like the following:

[
The *base direction* of each line in a cue (which is used by the Unicode Bidirectional Algorithm to determine the order in which to display the characters in the line) is determined by looking up the first strong directional character in each line, using the CSS plaintext algorithm.  In the occasional cases where the first strong character on a line would produce the wrong base direction for that line, the content author should use an RLM or LRM control character at the start of the line to correct it.

Where the base direction of some embedded text within a line needs to be different from the surrounding text on that line, this can be achieved by using the paired directional control characters provided by Unicode.

The baseline direction does not affect the alignment of the line within the cue box.  The default alignment for lines of text within a cue box is centred.  If you don't want to centre, but you want the alignment of the line to correspond to the script used (eg. Latin vs Arabic), you can set the WebVTT alignment cue setting for that cue box to start or end.  This will cause lines that start with a strong RTL character to align to the right, and otherwise align to the left. [an example would be good here] If you want the lines to be aligned the same way within the cue box, regardless of the base direction for the text in the line, set the alignment cue setting to left/right.

Another, higher level, aspect related to the direction of the text relates to whether the text flows horizontally within the cue box or vertically (in which case lines may flow either to the left, as in Mongolian, or to the right, as in Chinese, Korean and Japanese). This is determined by the declared writing direction. This affects the alignment of the cue box (the box, not the text) relative to the surrounding space through the WebVTT cue line alignment.  Values for the latter include 'start' and 'end', but this has nothing to do with the base direction of the actual text – these are simply abstractions that allow the positioning to transition between horizontal and vertical orientations. For example, start means left for horizontally set text, and top for vertically set text.
]

Note that the above uses the term 'base direction' to describe the direction that feeds the needs of the UBA.  It may help to make wider use of that term, given that most people will find 'text direction' confusing.

**Comment by zcorpan** [comment]
@r12a Thanks!! Please review the PR above.

**Comment by r12a** [comment]
sorry to be slightly late to the party. I reviewed this last week, but didn't have time to respond.  I took another look today and it seems good. I like the good use of examples. Thanks!

**Comment by zcorpan** [comment]
:+1:
