### ISSUE TITLE
Change syntax for cue id to a setting?

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#254]
The parser is a bit annoying because the id is before the timings. I think it would be better if the id was a setting of the cue instead, as in:

```
00:00:00.000 --> 00:00:02.000 id:foo
Hello world
```

This would restrict the id to not contain spaces.

For the parser, it would mean that a new block can just look at the first line to determine what kind of block it is, instead of checking the second line first to see if it contains `-->`. For instance, the following is a valid cue with the id "NOTE", which is a bit weird (and similarly for other block types we introduce):

```
NOTE
00:00:00.000 --> 00:00:02.000
Hello world
```

If we were to change this, then legacy files would have their IDs dropped on the floor (as invalid blocks terminated by a line that contains `-->` which starts a new cue).

Is it too late to change this? What do people think?

**Comment by Desiderius77** [comment]
You say : 

"This would restrict the id to not contain spaces."

I think this is very annoying ! This is a huge restriction for indexing for instance

**Comment by zcorpan** [comment]
@Desiderius77 thanks for the feedback! Can you elaborate on how indexing is typically done and why it is useful, or point to something I can look at?

**Comment by Desiderius77** [comment]
What I wanted to say is that identifiers are useful to index subtitles 
and to allow final user to search using this index.

For example : 

WEBVTT

Evolution of the Web
00:00:00.000 --> 00:01:00.000
The World Wide Web has been created by Sir Berners Lee in 1990

allows you to search "Evolution" or "Web"

with the syntax you propose ( if I well understand )

00:00:00.000 --> 00:01:00.000 id:Evolution_of_the_Web
The World Wide Web has been created by Sir Berners Lee in 1990

you can no more search "Evolution" or "Web" but know exactly the id "Evolution_of_the_Web"

Another annoying fact is that this syntax differs from the Subrip syntax and it makes the transformation from Subrip to WebVTT more difficult.

I do not understand very well what is the problem for the parser to look at the second line.
I have made many scripts using AWK to transform Subrip files and it was not difficult
to skip one line to find the timing informations.

**Comment by zcorpan** [comment]
OK so you assume an indexer that allows you to search for full words only? It seems Mac OS X allows partial-word search, but I suppose that might not be the case everywhere.

The indexing use case could also be solved with NOTE blocks (unless you want to be able to search in JS from the information provided via the DOM API).

```
WEBVTT

NOTE
Evolution of the Web

00:00:00.000 --> 00:01:00.000
The World Wide Web has been created by Sir Berners Lee in 1990
```

I agree that conversion from SRT is slightly harder.

**Comment by nigelmegitt** [comment]
I would prefer to separate indexable/searchable metadata from IDs also. 

Looking at the syntax of the id, I would propose to restrict the syntax of the id field to be coincident with [NCName](http://www.w3.org/TR/xml-names11/#NT-NCName) as used for `xml:id` to make interoperability easier - since you've proposed using : as a delimiter that should work quite nicely. Hopefully the additional first character constraints would not be problematic.

**Comment by zcorpan** [comment]
WebVTT is not an XML format so I think it makes little sense to use XML constraints.

**Comment by silviapfeiffer** [comment]
The id is where it is because WebVTT's roots are in SRT, which also has it's id before the timings. The two formats have grown apart - probably sufficiently that we don't need to worry about this similarity (seeing as a conversion needs to already do a few more things than just moving a field).

Maybe we could just prefix an ID field, so it becomes easier to distinguish between the different types of "cues"?

```
NOTE
00:00:00.000 --> 00:00:02.000
Hello world

ID:hello
00:00:00.000 --> 00:00:02.000
Hello world
```

Then we can decide by the first few letters if it's supposed to be a cue or something else.

**Comment by zcorpan** [comment]
Then we'd have to require ID: on every cue, or not gain much.

Thinking about this more, I think WebVTT is wide-spread enough at this point that this change would be too disruptive to be worth it.
