### ISSUE TITLE
Out-of-range position value

### ISSUE THREAD

**Issue by alastor0325** [w3c/webvtt#289]
https://w3c.github.io/webvtt/#cues
> If the position is numeric, then return the value of the position and abort these steps

If the position value is out-of-range [0~100], what's value we should return to?
We should have a mechanism like #webvtt-cue-line's, returning a default value when it's out-of-range.

**Comment by zcorpan** [comment]
As far as I can tell it can't end up being out of range. Parsing throws out out-of-range values, and the DOM API throws for out of range values.

This is different from "line" because the DOM API would be hard to use if it would throw for out-of-range values; when snap-to-lines flag is true, any value should be allowed, and otherwise you only want to use in-range values, but it should still be possible to set the `line` and `snapToLines` IDL attributes in either order.

See https://www.w3.org/Bugs/Public/show_bug.cgi?id=16917

Let me know if you would like this clarified in a note in the spec.

**Comment by alastor0325** [comment]
Hi, @zcorpan,
Sorry for my delay reply.

Thanks your explanation.
But I'm wondering whether we can mention that (throwing our-of-range error) in the spec since I didn't find related description in the spec.

Thanks again!

**Comment by alastor0325** [comment]
Also, I have another question,

In [1], we would return 100 when the line value is negative. However, the comment 1 in [2] said that we should return the error. Which one is correct?

In addition, if the following code should throw error, why we don't mention that in spec?
```
cue.snapToLines = true;
cue.line = -1;
cue.snapToLines = false; // throw??
```

Thanks!

[1]  https://w3c.github.io/webvtt/#webvtt-cue-line
[2]  https://www.w3.org/Bugs/Public/show_bug.cgi?id=16917

**Comment by zcorpan** [comment]
OK, I can clarify this in the spec.

https://www.w3.org/Bugs/Public/show_bug.cgi?id=16917 was fixed in the opposite way than what was suggested in the first comment; see comment 6. So `snapToLines` should *not* throw.

**Comment by zcorpan** [comment]
Thanks you, please see
https://w3c.github.io/webvtt/#webvtt-cue-line
https://w3c.github.io/webvtt/#dom-vttcue-line

**Comment by alastor0325** [comment]
Thanks you too :)
