### ISSUE TITLE
Question about cue position and control interface

### ISSUE THREAD

**Issue by alastor0325** [w3c/webvtt#294]
https://w3c.github.io/webvtt/#processing-model

> If the user agent is exposing a user interface for video, add to output one or more completely transparent positioned CSS block boxes that cover the same region as the user interface\.
> 
> If the last time these rules were run, the user agent was not exposing a user interface for video, but now it is, optionally let reset be true\. Otherwise, let reset be false\.

The definition about "exposing a user interface" in [1] is the controls attribute is set. However, this attribute can't reflect the displaying status of control interface.

In most browser, the video control interface would appear when the cursor is hovering up the video, and disappear after a while the cursor hovered out.

So, the questions are
(1) Does the "exposing a user interface" here means "displaying a user interface" instead of "controls=ture"?
(2) Does that means we should adjust the cue position every time when the displaying status of user interface changed? 
(3) If we adjust the cue position when the user interface displays, after the 
user interface disappear, should we adjust cue position again? or keep its original position?

For question2, here is a example,
http://people.mozilla.org/~alwu/WebVTT/vttExample.html
The cue would overlap with control interface in Chrome and Opera, but the cue would adjust its position in Safari to avoid overlapping.

Is Safari behavior correct?

Thanks!

[1] https://html.spec.whatwg.org/multipage/embedded-content.html#expose-a-user-interface-to-the-user

**Comment by zcorpan** [comment]
> (1) Does the "exposing a user interface" here means "displaying a user interface" instead of "controls=ture"?

Exposing a user interface, as defined in HTML, is indeed separate from the `controls` attribute. For example, if scripting is disabled, the HTML spec says that user agents should expose a user interface even if there is no `controls` attribute, or the user can choose to enable the UI from e.g. the context menu.

For the purpose of the WebVTT spec, it is indeed relevant whether the controls are actually currently being displayed. In the HTML spec it is slightly ambiguous whether the user agent is considered to "expose a user interface" in the case where they are available on hover but are currently hidden.

> (2) Does that means we should adjust the cue position every time when the displaying status of user interface changed? 

Yes, but it's optional ("optionally let reset be true").

> (3) If we adjust the cue position when the user interface displays, after the 
user interface disappear, should we adjust cue position again? or keep its original position?

The WebVTT spec says to not reset when the controls go from visible to not visible ("Otherwise, let reset be false.").

So, as far as I can tell, all browsers are correct for the case when the controls go from hidden to visible, since moving the cues is optional. But Safari is wrong for moving the cues again when the controls go from visible to hidden. Maybe the spec should be changed to allow that, though?

**Comment by alastor0325** [comment]
After reading your explanation, I think "not reset when the controls go from visible to not visible" is better, we should keep it because it seems too annoying if we change the control interface frequently.
Thanks again!

**Comment by zcorpan** [comment]
👍
