### ISSUE TITLE
AlignSetting values don't match what has been implemented in UAs

### ISSUE THREAD

**Issue by smaug----** [w3c/webvtt#301]
See https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/html/track/vtt/VTTCue.idl?q=VTTCue.idl&sq=package:chromium&l=36
and http://mxr.mozilla.org/mozilla-central/source/dom/webidl/VTTCue.webidl#12
and http://trac.webkit.org/browser/trunk/Source/WebCore/html/track/VTTCue.cpp#L428

For some reason the spec has "center" but implementations "middle". It is unclear whether it is safe to change implementations and are others than Gecko considering the change.
https://bugzilla.mozilla.org/show_bug.cgi?id=1276130

**Comment by zcorpan** [comment]
See https://github.com/w3c/webvtt/pull/244

Since @foolip and @eric-carlson supported the change, I assume they are willing to change this in Chromium and WebKit. (Do you have bugs filed for this?)

Since center is the default value, any content that uses `align:middle` in the syntax will have the same result. The DOM API could in theory break something, but I believe that is used so little that it is unlikely to break anything in practice.

Looking in httparchive (495k pages) for "new VTTCue(" and ".align" I get 14 results, of which 1 seems to do something with `.align` at all

> http://www.holacdn.com/	http://player.h-cdn.com/player_vjs5.js?md5=759476-d6135e06

...but as far as I can tell even this script will not break if the change is implemented -- setting `align` to an unknown value is ignored:

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4255

...and the script later has this:

```
{textAlign:cue.align==="middle"?"center":cue.align, ...
```

...which, if the browser's default changes to "center", will still correctly set `textAlign` to `center`. (After the change is implemented this can be simplified to `{textAlign:cue.align, ...`, which was sort of the point of the spec change.)

**Comment by eric-carlson** [comment]
> Since @foolip and @eric-carlson supported the change, I assume they are willing to change this in Chromium and WebKit. (Do you have bugs filed for this?)


https://bugs.webkit.org/show_bug.cgi?id=158478

**Comment by alastor0325** [comment]
Here is the Gecko bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1276130

**Comment by zcorpan** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=617989

**Comment by alastor0325** [comment]
FYI, We have already used the "center" for the AlignSetting in Gecko.

**Comment by zcorpan** [comment]
Great, thanks. Closing this then.
