### ISSUE TITLE
Add Security and Privacy Considerations section

### ISSUE THREAD

**Issue by dwsinger** [w3c/webvtt#323]
add the following section:

X Security and Privacy Considerations

X.1 Text-based format security

As with any text-based format, it is possible to construct malicious content that might cause buffer over-runs, value overflows (e.g. string representations of integers that overflow a given word length), and the like. Implementers should take care that over-long lines,  field values, or encoded values do not cause security problems.

X.2 Styling

VTT can embed style ‘snippets’, and they in turn can cause the loading of external style sheets through the use of a CSS “@import” rule, in user-agents that support CSS.  Under these circumstances, the security and privacy considerations of CSS apply.  In addition, it is possible for a user-agent to offer user style-sheets, and their presence and nature might be detectable by scripts running in the same user-agent (e.g. browser). This might enable fingerprinting of the user or reveal aspects of the user’s preferences (e.g. the choice of a large font size and/or high-contrast colors might indicate a user with visual impairments).

X.3 Scripting

VTT does not include or enable scripting. However, it is possible to construct and deliver a file that is designed not to present captions or subtitles, but instead to provide timed input (‘triggers’) to a script system. A poorly-written script or script system might then cause security or other problems; however, this consideration really applies to the script system.  Because VTT supplies these triggers at their timestamps, a malicious file might present such triggers very rapidly, perhaps causing undue resource consumption.

X.4 Privacy of preference

A user-agent that selects, and causes to download or interpret a VTT file, might indicate to the origin server that the user has a need for captions or subtitles. That is a (small) piece of information about the user. However, the offering of a caption file, and the choice whether to retrieve and consume it, are better viewed as characteristics of the format or protocol which does the offer (e.g. the HTML <source> element), rather than of the caption format itself.

**Comment by nigelmegitt** [comment]
Thanks for raising this @dwsinger - a few early review comments from me:

s/VTT/WebVTT/g

> As with any text-based format, it is possible to construct malicious content 

I'm not clear what this has to do with text-based formats. If there are specific parts of WebVTT that are not fully specified then the spec needs to be improved - for example are all data types well defined in terms of permitted bytes and interpretations, range limits etc? Assuming that they are  well defined then any parser needs to be implemented properly so that it does not suffer these kinds of problem. So the second sentence is correct. I'm not sure if this is really worth saying though - it's equivalent to: implementations should be written properly. Doesn't seem to add much useful value.

I have raised the point elsewhere that from an overall architectural perspective the need for a new bespoke custom parser for a new format increases the likelihood of security issues arising; another factor here is the maturity and usage of the parser and implementations that exist. Neither of these points is caused by the spec per se though, so I'm not really sure what useful thing can be added to the security and privacy section about this.

I guess general advice that implementations should be tested and be well behaved in the presence of out of range values etc is worth keeping.

> VTT does not include or enable scripting. 

This could be a TextTrack issue rather than a VTT one, but in many cases VTT will be accompanied by scripts, particularly if used in an HTML context to deliver a non-standard experience or one based on metadata cues. It would be worth saying that this usage pattern is expected to be commonplace and the loading and running of such scripts could be used to reveal information about the user; it is a potential privacy issue.

>  Because VTT supplies these triggers at their timestamps, a malicious file might present such triggers very rapidly, perhaps causing undue resource consumption.

Isn't this an issue with Text Track and Text Track Cue rather than VTT itself? Not all Text track cues are VTTCues, at least in principle.

> However, the offering of a caption file, and the choice whether to retrieve and consume it, are better viewed as characteristics of the format or protocol which does the offer (e.g. the HTML element), rather than of the caption format itself.

The choice of the "better view" is surely in the eye of the beholder? Probably better not to speculate about this. The fact is that loading a specific type of resource like a WebVTT file may reveal information about the user.

**Comment by dwsinger** [comment]
Hi Nigel, thanks

> On Jan 24, 2017, at 15:35 , Nigel Megitt <notifications@github.com> wrote:
> 
> Thanks for raising this @dwsinger - a few early review comments from me:
> 
> s/VTT/WebVTT/g
> 
> As with any text-based format, it is possible to construct malicious content
> 
> I'm not clear what this has to do with text-based formats.

Text-based formats have to be parsed; textual representations of integers parsed into binary, strings stored in buffers and so on.  One can both overflow 32-bits (for example) and overflow string buffers.  Buffer overflow or value overflow are such common attack techniques that I thought them worth mentioning.

> If there are specific parts of WebVTT that are not fully specified then the spec needs to be improved - for example are all data types well defined in terms of permitted bytes and interpretations, range limits etc? Assuming that they are well defined then any parser needs to be implemented properly so that it does not suffer these kinds of problem.

No disagreement here.  I’m not aware of under-specified parts.

> So the second sentence is correct. I'm not sure if this is really worth saying though - it's equivalent to: implementations should be written properly. Doesn't seem to add much useful value.

well, it’s a vulnerability and worth mentioning, IMHO

> 
> I have raised the point elsewhere that from an overall architectural perspective the need for a new bespoke custom parser for a new format increases the likelihood of security issues arising; another factor here is the maturity and usage of the parser and implementations that exist. Neither of these points is caused by the spec per se though, so I'm not really sure what useful thing can be added to the security and privacy section about this.
> 
> I guess general advice that implementations should be tested and be well behaved in the presence of out of range values etc is worth keeping.
> 
> VTT does not include or enable scripting.
> 
> This could be a TextTrack issue rather than a VTT one, but in many cases VTT will be accompanied by scripts, particularly if used in an HTML context to deliver a non-standard experience or one based on metadata cues. It would be worth saying that this usage pattern is expected to be commonplace and the loading and running of such scripts could be used to reveal information about the user; it is a potential privacy issue.
> 
> Because VTT supplies these triggers at their timestamps, a malicious file might present such triggers very rapidly, perhaps causing undue resource consumption.
> 
> Isn't this an issue with Text Track and Text Track Cue rather than VTT itself? Not all Text track cues are VTTCues, at least in principle.

yes, again, formally, it’s a problem of how the format is used rather than the format per se, but it’s a close-enough problem to be worth pointing out, IMHO

> 
> However, the offering of a caption file, and the choice whether to retrieve and consume it, are better viewed as characteristics of the format or protocol which does the offer (e.g. the HTML element), rather than of the caption format itself.
> 
> The choice of the "better view" is surely in the eye of the beholder? Probably better not to speculate about this.

Poor choice of words on my part.  If a DASH MPD offers captions, and the user is observed to have requested easy-to-read captions, this reveals something about the user (the user might have a hearing and/or comprehension problem).  Again, this is best considered a problem of DASH rather than of the VTT format per se, but again, it’s close enough to be worth mentioning.


> The fact is that loading a specific type of resource like a WebVTT file may reveal information about the user.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Singer
Manager, Software Standards, Apple Inc.

**Comment by nigelmegitt** [comment]
> Text-based formats have to be parsed

Sorry I wasn't clear enough: I meant that _all_ formats have to be parsed; in general non-text binary formats are specified in a more tied down way though, e.g. the _n_ bits beginning at address _x_ represent some specific piece of information, but quite often they use, say, key/length/value syntax which could potentially also be open to similar problems. 

> this is best considered a problem of DASH rather than of the VTT format per se

I'd generalise this to any format that makes resource requests that can reveal something about user choices, rather than calling out DASH. But aside from that detail point, yes, generally WebVTT may be used in such a context and thus the mere requesting of a WebVTT resource may reveal information about the user. Then the presentation of that resource may reveal further information, as you have said by causing other resources such as stylesheets, fonts etc to be loaded.

**Comment by dwsinger** [comment]
> On Jan 24, 2017, at 17:07 , Nigel Megitt <notifications@github.com> wrote:
> 
> Text-based formats have to be parsed
> 
> Sorry I wasn't clear enough: I meant that all formats have to be parsed; in general non-text binary formats are specified in a more tied down way though, e.g. the n bits beginning at address x represent some specific piece of information, but quite often they use, say, key/length/value syntax which could potentially also be open to similar problems.

OK.  Integer overflow doesn’t happen in binary formats, but strings are a source of endless problem everywhere (and integer limits).

> 
> this is best considered a problem of DASH rather than of the VTT format per se
> 
> I'd generalise this to any format that makes resource requests that can reveal something about user choices, rather than calling out DASH. But aside from that detail point, yes, generally WebVTT may be used in such a context and thus the mere requesting of a WebVTT resource may reveal information about the user. Then the presentation of that resource may reveal further information, as you have said by causing other resources such as stylesheets, fonts etc to be loaded.
> 

Yes, I don’t think the privacy considerations chapter should mention DASH per se.

David Singer
Manager, Software Standards, Apple Inc.

**Comment by dwsinger** [comment]
after that discussion, change the last section to

X.4 Privacy of preference

A user-agent that selects, and causes to download or interpret a VTT file, might indicate to the origin server that the user has a need for captions or subtitles. That is a (small) piece of information about the user. However, the offering of a caption file, and the choice whether to retrieve and consume it, are really characteristics of the format or protocol which does the offer (e.g. the HTML element), rather than of the caption format itself.

**Comment by nigelmegitt** [comment]
Guys, there was a good bit of debate about the draft text for this section earlier and my comment that the format security is not restricted to text based formats appears to have been ignored in the updates that were merged. As far as I can tell any parser in general can suffer these kinds of problems.

**Comment by zcorpan** [comment]
Would it address your concern to remove "text-based"?

**Comment by nigelmegitt** [comment]
> Would it address your concern to remove "text-based"?

@zcorpan yes it would, but on reflection I agree that WebVTT is in fact a text-based format so, with apologies for the noise, I'm going to close this again without requiring or requesting a further change; if I see anything else that could be improved I'll open a new issue.
