### ISSUE TITLE
webvtt-cue-timestamp, ">" character is mandatory?

### ISSUE THREAD

**Issue by bechen** [w3c/webvtt#342]
https://github.com/w3c/web-platform-tests/blob/master/webvtt/parsing/cue-text-parsing/tests/timestamps.html 
The testcase input missing the ">" character such as "<00:00.500". It seems conflict to the spec?
https://w3c.github.io/webvtt/#webvtt-cue-timestamp

**Comment by fsoder** [comment]
No, that is only the syntax specification, what's relevant here is the parsing (tokenization) step:
> End-of-file marker
>Return a timestamp tag whose tag name is result and abort these steps.

https://w3c.github.io/webvtt/#webvtt-timestamp-tag-state

**Comment by zcorpan** [comment]
What @fsoder said. We could change this to drop incomplete tokens, but it doesn't matter so much either way I think.

**Comment by rillian** [comment]
To clarify from my own check of this, the web platform test is correct because the value without closing `>` comes at the end of the file. It would fail if there were a subsequent queue, but the parser treats end-of-file like end-of-tag.

The test should probably verify that, and verify that correctly-delimited timestamp tags with invalid values (`<00> test`, `<0 foo bar> test`, etc.) are correctly dropped.
