### ISSUE TITLE
Wide Review Comment 2017: Distinction between cue payload types

### ISSUE THREAD

**Issue by tairt** [w3c/webvtt#363]
In most cases it can not be said if cue payload is `WebVTT metadata text`, `WebVTT cue text` (in which case it would be of payload type `WebVTT cue text`) or `WebVTT chapter title text`. The only difference seems to be the allowance/disallowance of the AMPERSAND character and the LESS-THAN SIGN character. 

According to the file types definition in section 4.6 a WebVTT file using cue text is also a WebVTT file using metadata content and a WebVTT file using chapter title text. It seems that the distinction makes only sense if this is signaled externally.

**Comment by dwsinger** [comment]
I think it makes sense to say that it's the environment (i.e. external signal) that tells you. I wonder if we should eliminate the differences (the allowance/disallowance of the AMPERSAND character and the LESS-THAN SIGN character)?

**Comment by silviapfeiffer** [comment]
We had this discussion a very long time ago, see https://www.w3.org/Bugs/Public/show_bug.cgi?id=18657 "WebVTT: add file-wide default kind specification".

I am personally in two minds about this.

**1/ The case against a content-usage metadata field**
A file's usage should not be constraint by the file itself.
It should be the tools that are managing, manipulating and rendering the file that should decide how the file is to be interpreted.
The file should merely contain valid syntax and be interpreted for manipulation and rendering in its context.
If you need this information, you can always add a NOTE section to the file.

**2/ The case for a content-usage metadata field**
WebVTT files are able to specify files that need vastly different rendering and manipulation (chapters, captions, descriptions, metadata).
Tools that need to manipulate WebVTT files could rely on less environmental information if this information was indicated in the file itself.
In a non-HTML environment, often the video and WebVTT file is all that is provided, so environmental information needs to be "made up" if it cannot be deduced from the WebVTT file itself.
There is also precedent about such content indication in HTML where the language is indicated in a global lang attribute (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Language).

I myself tend towards desiring a content-usage field in WebVTT. It is, however, strictly not required because we have an ability to add any kind of comments to a WebVTT file, so anyone who desires to indicate content-usage in a WebVTT can right now add this to their WebVTT files, e.g.
NOTE
kind: captions

Standardisation of such kind of content can be pursued in a later version of WebVTT. This should not hold up the V1.0 process.

**Comment by silviapfeiffer** [comment]
FYI: This issue was closed because it had been resolved previously in the CG for the v1 WebVTT spec and it was determined to delay this for v2, as documented above.

Therefore, following https://www.w3.org/wiki/TimedText/WebVTT_Wide_Review#Guidelines_for_Status_of_comments , the CG processing resolution is:

2.7- Done but comment Rejected

And the classification of the issue is:
c- substantive

**Comment by dwsinger** [comment]
would like to know if we should retain this minor difference: "The only difference seems to be the allowance/disallowance of the AMPERSAND character and the LESS-THAN SIGN character." A conformance checker would need to know the usage in order to check this.

**Comment by tairt** [comment]
@silviapfeiffer Thanks for detailed explanation and the pointers to the discussions in the past. My intent was not to propose a substantive change and a new feature to signal the file type. It was just the observations that it is confusing that in the syntax chapter the spec distinguish three different file types although there are actually no or nearly no syntax differences.  Therefore an informative note may do it. I think the proposal from @dwsinger 

> I think it makes sense to say that it's the environment (i.e. external signal) that tells you.

would do exactly what is needed.

**Comment by silviapfeiffer** [comment]
In reply to the difference between the three types of cue payload - I don't see where you're reading that the difference is the allowance/disallowance of the AMPERSAND and LESS-THAN SIGN characters. Section 4.6 explains the differences:
* `WebVTT cue text` allows all the `WebVTT cue components`
* `WebVTT chapter title text` allows only the `WebVTT cue text span` and HTML character references
* `WebVTT metadata text` allows any text
None of them allow `-->`

I can certainly add a comment about the "external signalling" for now.

**Comment by silviapfeiffer** [comment]
@tairt please review if the new patch satisfies your needs.

**Comment by tairt** [comment]
Possibly the point I want to make is still not clear enough.

The syntax restriction for the different file types are quite the same. So in most cases you could not distinguish one from the other (e.g. the below file could be of all three types, unless I missed something).

Therefore you can not infer from the syntax the type of the file. This could only be done out-of-band by the context. 

But although I doubt that the type definition makes sense in the syntax section, it also has no serious impact and you may just close this issue.

```
WEBVTT

test
00:00.000 --> 00:02.000
This is a test.

123
00:00.000 --> 00:02.000
That’s an, an, that’s an L!

crédit de transcription
00:04.000 --> 00:05.000
Transcrit par Célestes™

```

**Comment by silviapfeiffer** [comment]
@tairt the external signaling of the current type isn't going to change at this point. It is, however, possible to add a metadata description into a NOTE at the beginning of the file that makes that clear. In future we may specify such a tag.

And yes, there are very simple, basic WebVTT files that could well be of any of the listed types, but I don't see an issue with that.

Can we land the patch and close the bug as being addressed through the patch? I think the patch is clarifying the different file types and allows authors more easily to distinguish between them.

**Comment by tairt** [comment]
> And yes, there are very simple, basic WebVTT files that could well be of any of the listed types, but I don't see an issue with that.
I think syntax wise nearly all WebVTT files could be of one of the three types. 

> Can we land the patch and close the bug as being addressed through the patch? 
Thanks a lot for your efforts. It does not really address my comments but that is OK. My point was, that you can not distinguish the different type well enough by syntax and chapter 4.6 gives this impression. As there is also standard way to signal the file type, the question is if this section makes sense at all.

But I think there are more important issues than that and there is also no harm in leaving it like it is. I therefore closing the issue that I opened.

**Comment by tairt** [comment]
I am fine with moving on and leave the spec as is. It is OK for me to label this comment as "won't fix" or "rejected".

**Comment by silviapfeiffer** [comment]
Thanks.
