### ISSUE TITLE
Wide Review Comment 2017: future styling options mechanism

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/webvtt#373]
Copy/paste from https://lists.w3.org/Archives/Public/public-tt/2017Sep/0080.html - raising as an issue for tracking/disposition purposes.

The list of ::cue CSS properties in §7.2.1 is a useful minimal set, especially for a non-CSS-based implementation however the requirement to ignore any properties not in the list seems overly restrictive for a CSS based implementation. What is the mechanism for adding further styling options in the future, given that WebVTT files do not indicate any specification version?

**Comment by silviapfeiffer** [comment]
Further styling options would just be added to the list. It's good to be restrictive for non-browsers and for browsers to also stick to the list otherwise you do not get compatible rendering between browser and non-browser implementation.
I don't see an issue with adding new styling options in the future - both, browsers and non-browser then have to do some work (one a little less than the other) to support that new feature.
I'd like to close this as "works for me".

**Comment by silviapfeiffer** [comment]
add some text to the authoring section that explains that the applicable CSS is limited to cover UAs that are non-browsers

**Comment by silviapfeiffer** [comment]
Waiting for feedback from @nigelmeggit before landing and closing. Thanks.

**Comment by nigelmegitt** [comment]
Ah, @silviapfeiffer you mean me and my hard-to-spell name @nigelmegitt ! Comment added.

**Comment by silviapfeiffer** [comment]
@nigelmegitt so sorry! I share that - everyone calls me Sylvia. Sorry!

**Comment by dwsinger** [comment]
agreed in principle, we're just fiddling with words
