### ISSUE TITLE
Wide Review Comment 2017: unspecified edge margins make accurate positioning impossible

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/webvtt#379]
Copy/paste from https://lists.w3.org/Archives/Public/public-tt/2017Sep/0080.html - raising as an issue for tracking/disposition purposes.

The user-agent defined edge margins used in section 6 Rendering effectively mean that the author of the file can not predict positions or line breaks accurately since the size and position of text cannot be known at authoring time. This prevents the author from being able to position captions in a location that avoids overlapping parts of the video that are important for the viewer to see in order to understand the content. This makes it effectively impossible to meet the BBC's [editorial subtitle guidelines](http://bbc.github.io/subtitle-guidelines/#Positioning) using WebVTT. Note that this comment must logically only apply when a single track is visible since WebVTT defines rules for multiple tracks being displayed simultaneously, in which case positioning is presumably outside the realm of the subtitle author, in the general case.

As an alternative to edge margins, why not allow the something like the padding property to be set on whatever viewport is used as the positioning reference area? (cf comment above about positioning relative to video or to video viewport) By the way, from a CSS box model perspective, calling them "margins" is confusing – aren't they "padding" values since they are inset from the video viewport area?

**Comment by silviapfeiffer** [comment]
The edge margin was defined to address overscan. A captioning author has generally no idea if there is overscan in the video - the only entity involved in the steps necessary to render captions on top of video that knows whether there is overscan is the browser. Therefore, this gives the browser a chance to deal with overscan and allow the caption to be visible. E.g. when a caption author specifies that a cue is to be rendered at the left edge of the video, then with the left edge of the video being off screen, the cue may actually be partially invisible.

This is to deal with faulty authored caption files. I don't expect that would be the case with files coming from the BBC, so any explicit positioning provided in a BBC file would be rendered accurately.

Incidentally, the edge margin is exactly a kind of padding on the viewport. The way it is specified, it's a margin on the initial containing block for the captions rather than a padding on the viewport.
I'd be happy to add an explanatory sentence about how this influences the size of the initial containing block for the captions to address overscan. Would that be acceptable?

**Comment by silviapfeiffer** [comment]
Note that CEA-608 defines a safe caption area as 80% of the TV picture height and 80% of TV picture width, centered. This is merely following in that footstep.

**Comment by nigelmegitt** [comment]
> I'd be happy to add an explanatory sentence about how this influences the size of the initial containing block for the captions to address overscan. Would that be acceptable?

That would be a helpful change, thank you.

Overall though the problem continues that there is no defined fixed relationship between positions on the video and in the subtitles or captions. This is not a problem limited to WebVTT by the way. This has been resolved (to the extent that it can be) in IMSC 1.0.1 by introducing the concept of a signalled active area, i.e. the area within the defined video which is occupied by editorially important parts of subtitles or captions. This allows implementations, if they are overscanning or otherwise scaling or transforming the video, to know if that also will crop those captions, and possibly make a better choice about how to position the caption viewport over the video. There's definitely room here for allowing some implementation flexibility, but at the same time a "specified" fixed relationship between positions in the timed text file and positions in the video is extremely desirable.

**Comment by dwsinger** [comment]
consider replacing or augmenting "In the absence of overscan, this value should be picked for aesthetics (to avoid text being aligned precisely on the left or right edge of the video, which can be ugly)." with a statement for a recommended/mandatory value for edge margin.

**Comment by silviapfeiffer** [comment]
This sentence is problematic giving each UA a free hand:
"In the absence of overscan, this value should be picked for aesthetics (to avoid text being aligned precisely on the left or right edge of the video, which can be ugly)."

Resolution at TPAC: add a default edge margin of 0px instead of the above sentence ? (find out what the different UAs have implemented right now)

**Comment by silviapfeiffer** [comment]
We've received some feedback and I've done some research:

**John Birch from screensystems:**
For SD resolution...50 pixels left and right (~7%... [50/720 * 100])
For HD resolution...240 pixels left and right
N.B. These are often subsequently adjusted (tweaked) on a channel by channel basis to suit local requirements.
N.B. the HD values are intended to create a centred 4:3 style presentation. Even though the screen has a wider aspect ratio in HD, subtitles still tend to be maintained in a 4:3 presentation window in the screen centre to minimise eye movements - but this is up to the broadcasters... some choose to push the left and right margins closer to the screen edges. Our system, as is typical practise in subtitling, justifies to the set margins, rather than using absolute pixel positioning for the subtitles.

John also stated that: "with the introduction of HD and the use of ‘eye tracking’ research, it has been ‘determined’ that a more centred presentation enhances the reception (the readability) of the subtitles on larger display devices – so this placement is still a practical consideration rather than an aesthetic one."

**JB from videolan:**
We use 4% for all subtitles, but 0 for TTML and VTT.

**Chromium:**
The implementation is too old to cover that section of the spec, see https://chromium.googlesource.com/chromium/blink/+/master/Source/core/layout/LayoutVTTCue.cpp .
Therefore, the edgeMargin is 0.

**WebKit:**
It does not appear like there's use of an edge margin, see
https://github.com/WebKit/webkit/blob/master/Source/WebCore/rendering/RenderVTTCue.cpp
Therefore, the edgeMargin seems to be 0.
@eric-carlson would you agree?

**Comment by silviapfeiffer** [comment]
It seems, everything is possible from 0% to 18%, but 4%-10% seems common. I'd rather go for smaller, so how does 5% sit with everyone?

**Comment by dwsinger** [comment]
5% is the only number that has been volunteered for an actual implementation (CoreMedia), so I suggest we go with it!

**Comment by eric-carlson** [comment]
@silviapfeiffer 
> **WebKit:**
> It does not appear like there's use of an edge margin, see
> https://github.com/WebKit/webkit/blob/master/Source/WebCore/rendering/RenderVTTCue.cpp
> Therefore, the edgeMargin seems to be 0.
> @eric-carlson would you agree?
> 
Correct, WebKit does not add edge margin when positioning cues.

**Comment by eric-carlson** [comment]
@silviapfeiffer, @dwsinger:  I think we should use 0% to match the current behavior of WebKit, videolan, and (apparently) Chromium.

**Comment by silviapfeiffer** [comment]
in this case, we might as well just remove edge margin from the spec altogether and assume overscan is not necessary to deal with in this digital age.

**Comment by dwsinger** [comment]
true, but that has a larger scope of change. setting the initial value to 0 seems more appropriate given where we are

**Comment by silviapfeiffer** [comment]
it's in 4 places only.

BTW, just checked Firefox and I was't able to find edge margin there either:
https://hg.mozilla.org/mozilla-central/file/tip/dom/media/webvtt/vtt.jsm

**Comment by nigelmegitt** [comment]
I've +1ed @silviapfeiffer 's proposal to remove edge margin from the spec.

**Comment by dwsinger** [comment]
resolved, I think. set edge-margin to 0%, or remove it (which is functionally the same)

**Comment by dwsinger** [comment]
we just need to do the edit...(ok, "we" is a euphemism)

**Comment by silviapfeiffer** [comment]
I've now removed all mention of "edge margin" and of "margin" and of "overscan". Let me know if that meets expectations.

**Comment by silviapfeiffer** [comment]
#422 landed, so I'm ready to ask for "commenter-agreed" label and to close this issue

**Comment by nigelmegitt** [comment]
On the (probably not always valid) assumption that the content provider is able to control the video element size and the intrinsic size of the video content, this would work. That's not to say I'm not still concerned about video intrinsic size differing from video element size, but at least the content provider(s) can potentially make this work.

**Comment by silviapfeiffer** [comment]
That's how the web works: the final decision on how the page looks is with the web page author, and even then, the user can overruled again.

**Comment by nigelmegitt** [comment]
> That's how the web works

@silviapfeiffer It's not how video distribution works on the web though, where the video is often separately authored and distributed and simply embedded in a page, where the page author and the video provider are sometimes, but not always, the same organisation. This is a "world within a world" problem. I'm just calling out the mismatch here, no need to prolong the discussion further on this.
