### ISSUE TITLE
Cue identifier can't be matched by standard css rules

### ISSUE THREAD

**Issue by fcartegnie** [w3c/webvtt#403]
Because cue identifier isn't specified, it can start with a digit.

It prevents being tokenized/selected by parser following the CSS identifier naming 
(see CSS3 4.2. Tokenization for bnf)

```

ident | ::= | '-'? nmstart nmchar*
-- | -- | --
name | ::= | nmchar+
nmstart | ::= | [a-zA-Z] \| '_' \| nonascii \| escape


```

**Comment by fsoder** [comment]
From a parser PoV a cue identifier is specified: https://w3c.github.io/webvtt/#webvtt-cue-identifier (it can still be set to any string using the DOM TextTrackCue.id attribute though.)
So, yes it can start with a digit, and in that case care must be taken when writing a corresponding selector, so that the digit is escaped. (See Example 6, https://w3c.github.io/webvtt/#introduction-other-features)
