### ISSUE TITLE
The VTTRegion.lines attribute is a long type but cannot accept negative values

### ISSUE THREAD

**Issue by srirama179** [w3c/webvtt#414]
According to spec....
[region-lines](https://w3c.github.io/webvtt/#dom-vttregion-lines)
> The lines attribute, on getting, must return the WebVTT region lines of the WebVTT region that the VTTRegion object represents. On setting, if the new value is negative, then an IndexSizeError exception must be thrown. Otherwise, the WebVTT region lines must be set to the new value.

But according to webidl spec long type is ...
[long-type](https://heycam.github.io/webidl/#idl-long)
> The long type is a signed integer type that has values in the range [−2147483648, 2147483647].

So if we are not accepting negative values for lines, then how about changing its type to "unsigned long"?

**Comment by silviapfeiffer** [comment]
Fair enough

**Comment by k2nagaraju** [comment]
region-lines is updated to unsigned long, but latest spec. 
https://w3c.github.io/webvtt/#region-settings-parsing
contains "On setting, if the new value is negative, then an IndexSizeError exception must be thrown."

There is no chance setting negative value because of unsigned long in idl. 
So this info needs update

**Comment by silviapfeiffer** [comment]
ok, error throwing removed
